config/routes.rb
Myapp::Application.routes.draw do


  



  resources :brandteams
  resources :accounts
  resources :permisos
  resources :operacions
  resources :seccions
  resources :rols
  resources :showrooms do
      resources :showpins
      resources :archivofolders
  end
  resources :teams
  resources :archivofolders
  resources :documentos
  resources :folders do
    resources :archivofolders
  end
  resources :payments do
    collection {post :import}
  end

  
  resources :ventaunidads do
    collection {post :import}
  end
  
  resources :channels



  resources :skugraphs do
    collection {post :import}
  end
  
  resources :velocidaddiaria
  resources :archivos do
    get 'pdf', :on => :collection
  end
  
  resources :documents
  resources :assets
    devise_for :users

 # devise_scope :user do
  #get "sign_out", to: "devise/sessions#destroy"
#end
# Session routes for Authenticatable (default)

as :user do
  get 'users/profile', :to => 'devise/registrations#edit'
end
resources :skus
  #{:controller=>"devise/sessions", :action=>"destroy"}

  get 'products/jsontodb'
  resources :users
  resources :products do
    resources :variations
    resources :skus
    collection {post :import}
  end

  # You can have the root of your site routed with "root"
  root to: 'home#index'


  # All routes
  get "dashboards/dashboard_1"
  get "dashboards/dashboard_2"
  get "dashboards/dashboard_3"
  get "dashboards/dashboard_4"
  get "dashboards/dashboard_4_1"
  get "dashboards/dashboard_5"
  get "dashboards/channels"

  get "layoutsoptions/index"
  get "layoutsoptions/off_canvas"

  get "graphs/flot"
  get "graphs/morris"
  get "graphs/rickshaw"
  get "graphs/chartjs"
  get "graphs/chartist"
  get "graphs/peity"
  get "graphs/sparkline"
  get "graphs/c3charts"

  get "mailbox/inbox"
  get "mailbox/email_view"
  get "mailbox/compose_email"
  get "mailbox/email_templates"
  get "mailbox/basic_action_email"
  get "mailbox/alert_email"
  get "mailbox/billing_email"

  get "metrics/index"

  get "widgets/index"

  get "forms/basic_forms"
  get "forms/advanced"
  get "forms/wizard"
  get "forms/file_upload"
  get "forms/text_editor"
  get "forms/markdown"

  get "appviews/contacts"
  get "appviews/profile"
  get "appviews/profile_two"
  get "appviews/contacts_two"
  get "appviews/projects"
  get "appviews/project_detail"
  get "appviews/file_menager"
  get "appviews/vote_list"
  get "appviews/calendar"
  get "appviews/faq"
  get "appviews/timeline"
  get "appviews/pin_board"
  get "appviews/teams_board"
  get "appviews/social_feed"
  get "appviews/clients"
  get "appviews/outlook_view"
  get "appviews/blog"
  get "appviews/article"
  get "appviews/issue_tracker"
  get "appviews/team"

  get "pages/search_results"
  get "pages/lockscreen"
  get "pages/invoice"
  get "pages/invoice_print"
  get "pages/login"
  get "pages/login_2"
  get "pages/forgot_password"
  get "pages/register"
  get "pages/not_found_error"
  get "pages/internal_server_error"
  get "pages/empty_page"

  get "miscellaneous/notification"
  get "miscellaneous/nestablelist"
  get "miscellaneous/timeline_second_version"
  get "miscellaneous/forum_view"
  get "miscellaneous/forum_post_view"
  get "miscellaneous/google_maps"
  get "miscellaneous/code_editor"
  get "miscellaneous/modal_window"
  get "miscellaneous/validation"
  get "miscellaneous/tree_view"
  get "miscellaneous/chat_view"
  get "miscellaneous/agile_board"
  get "miscellaneous/diff"
  get "miscellaneous/sweet_alert"
  get "miscellaneous/idle_timer"
  get "miscellaneous/spinners"
  get "miscellaneous/live_favicon"
  get "miscellaneous/masonry"
  get "miscellaneous/tour"
  get "miscellaneous/loading_buttons"
  get "miscellaneous/clipboard"
  get "miscellaneous/truncate"
  get "miscellaneous/i18support"

  get "uielements/typography"
  get "uielements/icons"
  get "uielements/draggable_panels"
  get "uielements/resizeable_panels"
  get "uielements/buttons"
  get "uielements/video"
  get "uielements/tables_panels"
  get "uielements/tabs"
  get "uielements/notifications_tooltips"
  get "uielements/badges_labels_progress"

  get "gridoptions/index"

  get "tables/static_tables"
  get "tables/data_tables"
  get "tables/foo_tables"
  get "tables/jqgrid"

  get "commerce/products_grid"
  get "commerce/products_list"
  get "commerce/product_edit"
  get "commerce/product_detail"
  get "commerce/orders"
  get "commerce/cart"
  get "commerce/payments"

  get "gallery/basic_gallery"
  get "gallery/slick_carusela"
  get "gallery/bootstrap_carusela"

  get "cssanimations/index"

  get "landing/index"

end

app/models/variation.rb
class Variation < ActiveRecord::Base

	belongs_to :product

end

app/controllers/variations_controller.rb
class VariationsController < ApplicationController
  load_and_authorize_resource
  before_action :set_variation, only: [:show, :edit, :update, :destroy]

  # GET /variations
  # GET /variations.json
  def index
    @product = Product.find(params[:product_id])
    @variations = @product.variations
  end

  # GET /variations/1
  # GET /variations/1.json
  def show
    
  end

  # GET /variations/new
  def new
    @product = Product.find(params[:product_id])


    # Associate an item object with order 1
    @variation = @product.variations.build
  end

  # GET /variations/1/edit
  def edit
  end

  # POST /variations
  # POST /variations.json
  #def create
  # @variation = Variation.new(variation_params)
  #end



  def create
    @product = Product.find(params[:product_id])
    @variation = @product.variations.create!(variation_params)
   
    redirect_to @product
  end

  # PATCH/PUT /variations/1
  # PATCH/PUT /variations/1.json
  def update
    respond_to do |format|
      if @variation.update(variation_params)
        format.html { redirect_to @variation, notice: 'Variation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @variation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /variations/1
  # DELETE /variations/1.json
  def destroy
    @variation.destroy
    redirect_to "/products"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_variation
      @variation = Variation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def variation_params
      params.require(:variation).permit(:name, :product_id)
    end


end

app/helpers/variations_helper.rb
module VariationsHelper
end

app/views/variations/_form.html.erb
<%= form_for(@variation) do |f| %>
  <% if @variation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@variation.errors.count, "error") %> prohibited this variation from being saved:</h2>

      <ul>
      <% @variation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/variations/edit.html.erb
<h1>Editing variations</h1>

<% form_for([@product, variation]) do |f| %>
  <%= f.error_messages %>

  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.submit "Update" %>
  </p>
<% end %>

<%= link_to 'Show', product_variation_path(@product, @variation) %> |
<%= link_to 'Back', product_variations_path(@product) %>

app/views/variations/index.html.erb
<h1>Items in <%= @product.title %></h1>

<table>
  <tr>
    <th>Item name</th>
  </tr>

<% for variation in @variations %>
  <tr>
    <td><%= variation.name %></td>
    <td><%= link_to 'Show', product_variation_path(@product, variation) %></td>
    <td><%= link_to 'Edit', edit_product_variation_path(@product, variation) %></td>
    <td><%= link_to 'Destroy', product_variation_path(@product, variation), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New item', new_product_variation_path(@product) %>
<%= link_to 'Back to Order', @product %>

app/views/variations/new.html.erb
<h1>New item</h1>

<% form_for([@product, @variation]) do |f| %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.submit "Create" %>
  </p>
<% end %>

<%= link_to 'Back', product_variations_path(@product) %>

app/views/variations/show.html.erb
<h1>Item in <%= @product.title %></h1>

<p>
  <b>variation name:</b>
  <%= @variation.name %>
</p>


<%= link_to 'Edit', edit_product_variation_path(@product, @variation) %> |
<%= link_to 'Back', product_variations_path(@product) %>