config/routes.rb
Myapp::Application.routes.draw do


  



  resources :brandteams
  resources :accounts
  resources :permisos
  resources :operacions
  resources :seccions
  resources :rols
  resources :showrooms do
      resources :showpins
      resources :archivofolders
  end
  resources :teams
  resources :archivofolders
  resources :documentos
  resources :folders do
    resources :archivofolders
  end
  resources :payments do
    collection {post :import}
  end

  
  resources :ventaunidads do
    collection {post :import}
  end
  
  resources :channels



  resources :skugraphs do
    collection {post :import}
  end
  
  resources :velocidaddiaria
  resources :archivos do
    get 'pdf', :on => :collection
  end
  
  resources :documents
  resources :assets
    devise_for :users

 # devise_scope :user do
  #get "sign_out", to: "devise/sessions#destroy"
#end
# Session routes for Authenticatable (default)

as :user do
  get 'users/profile', :to => 'devise/registrations#edit'
end
resources :skus
  #{:controller=>"devise/sessions", :action=>"destroy"}

  get 'products/jsontodb'
  resources :users
  resources :products do
    resources :variations
    resources :skus
    collection {post :import}
  end

  # You can have the root of your site routed with "root"
  root to: 'home#index'


  # All routes
  get "dashboards/dashboard_1"
  get "dashboards/dashboard_2"
  get "dashboards/dashboard_3"
  get "dashboards/dashboard_4"
  get "dashboards/dashboard_4_1"
  get "dashboards/dashboard_5"
  get "dashboards/channels"

  get "layoutsoptions/index"
  get "layoutsoptions/off_canvas"

  get "graphs/flot"
  get "graphs/morris"
  get "graphs/rickshaw"
  get "graphs/chartjs"
  get "graphs/chartist"
  get "graphs/peity"
  get "graphs/sparkline"
  get "graphs/c3charts"

  get "mailbox/inbox"
  get "mailbox/email_view"
  get "mailbox/compose_email"
  get "mailbox/email_templates"
  get "mailbox/basic_action_email"
  get "mailbox/alert_email"
  get "mailbox/billing_email"

  get "metrics/index"

  get "widgets/index"

  get "forms/basic_forms"
  get "forms/advanced"
  get "forms/wizard"
  get "forms/file_upload"
  get "forms/text_editor"
  get "forms/markdown"

  get "appviews/contacts"
  get "appviews/profile"
  get "appviews/profile_two"
  get "appviews/contacts_two"
  get "appviews/projects"
  get "appviews/project_detail"
  get "appviews/file_menager"
  get "appviews/vote_list"
  get "appviews/calendar"
  get "appviews/faq"
  get "appviews/timeline"
  get "appviews/pin_board"
  get "appviews/teams_board"
  get "appviews/social_feed"
  get "appviews/clients"
  get "appviews/outlook_view"
  get "appviews/blog"
  get "appviews/article"
  get "appviews/issue_tracker"
  get "appviews/team"

  get "pages/search_results"
  get "pages/lockscreen"
  get "pages/invoice"
  get "pages/invoice_print"
  get "pages/login"
  get "pages/login_2"
  get "pages/forgot_password"
  get "pages/register"
  get "pages/not_found_error"
  get "pages/internal_server_error"
  get "pages/empty_page"

  get "miscellaneous/notification"
  get "miscellaneous/nestablelist"
  get "miscellaneous/timeline_second_version"
  get "miscellaneous/forum_view"
  get "miscellaneous/forum_post_view"
  get "miscellaneous/google_maps"
  get "miscellaneous/code_editor"
  get "miscellaneous/modal_window"
  get "miscellaneous/validation"
  get "miscellaneous/tree_view"
  get "miscellaneous/chat_view"
  get "miscellaneous/agile_board"
  get "miscellaneous/diff"
  get "miscellaneous/sweet_alert"
  get "miscellaneous/idle_timer"
  get "miscellaneous/spinners"
  get "miscellaneous/live_favicon"
  get "miscellaneous/masonry"
  get "miscellaneous/tour"
  get "miscellaneous/loading_buttons"
  get "miscellaneous/clipboard"
  get "miscellaneous/truncate"
  get "miscellaneous/i18support"

  get "uielements/typography"
  get "uielements/icons"
  get "uielements/draggable_panels"
  get "uielements/resizeable_panels"
  get "uielements/buttons"
  get "uielements/video"
  get "uielements/tables_panels"
  get "uielements/tabs"
  get "uielements/notifications_tooltips"
  get "uielements/badges_labels_progress"

  get "gridoptions/index"

  get "tables/static_tables"
  get "tables/data_tables"
  get "tables/foo_tables"
  get "tables/jqgrid"

  get "commerce/products_grid"
  get "commerce/products_list"
  get "commerce/product_edit"
  get "commerce/product_detail"
  get "commerce/orders"
  get "commerce/cart"
  get "commerce/payments"

  get "gallery/basic_gallery"
  get "gallery/slick_carusela"
  get "gallery/bootstrap_carusela"

  get "cssanimations/index"

  get "landing/index"

end

app/models/ventaunidad.rb
class Ventaunidad < ActiveRecord::Base


def self.search(search)
  if search
    where('mes LIKE ?', "%#{search}%")
  else
    all
  end
end

	def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |ventaunidad|
        csv << ventaunidad.attributes.values_at(*column_names)
      end
    end
  end
  
require 'roo'

def self.import(file)
  if file != nil
  CSV.foreach(file.path, headers: true) do |row|
    Ventaunidad.create! row.to_hash
  end
  else
    @mensaje = "hola";
  end
end



  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
    when ".csv" then Roo::Csv.new(file.path, nil, :ignore)
    when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
    when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore)
    else raise "Unknown file type: #{file.original_filename}"
    end
  end


end

app/controllers/ventaunidads_controller.rb
class VentaunidadsController < ApplicationController
  load_and_authorize_resource
  before_action :set_ventaunidad, only: [:show, :edit, :update, :destroy]

  # GET /ventaunidads
  # GET /ventaunidads.json
  def index
    @ventaunidads = Ventaunidad.all
    @ventaunidads = Ventaunidad.search(params[:search]).paginate(:per_page => 20, :page => params[:page])
  end

  def import
    Ventaunidad.import(params[:file])
    redirect_to "/ventaunidads", notice: "Sales imported."
  end

  # GET /ventaunidads/1
  # GET /ventaunidads/1.json
  def show
  end

  # GET /ventaunidads/new
  def new
    @ventaunidad = Ventaunidad.new
  end

  # GET /ventaunidads/1/edit
  def edit
  end

  # POST /ventaunidads
  # POST /ventaunidads.json
  def create
    @ventaunidad = Ventaunidad.new(ventaunidad_params)

    respond_to do |format|
      if @ventaunidad.save
        format.html { redirect_to @ventaunidad, notice: 'Ventaunidad was successfully created.' }
        format.json { render action: 'show', status: :created, location: @ventaunidad }
      else
        format.html { render action: 'new' }
        format.json { render json: @ventaunidad.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ventaunidads/1
  # PATCH/PUT /ventaunidads/1.json
  def update
    respond_to do |format|
      if @ventaunidad.update(ventaunidad_params)
        format.html { redirect_to @ventaunidad, notice: 'Ventaunidad was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @ventaunidad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ventaunidads/1
  # DELETE /ventaunidads/1.json
  def destroy
    @ventaunidad.destroy
    respond_to do |format|
      format.html { redirect_to ventaunidads_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    
    def sort_column
      Ventaunidad.column_names.include?(params[:sort]) ? params[:sort] : "mes"
    end
  
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end

    def set_ventaunidad
      @ventaunidad = Ventaunidad.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ventaunidad_params
      params.require(:ventaunidad).permit(:mes, :valor)
    end
end

app/helpers/ventaunidads_helper.rb
module VentaunidadsHelper
end

app/views/ventaunidads/_form.html.erb
<%= form_for(@ventaunidad) do |f| %>
  <% if @ventaunidad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ventaunidad.errors.count, "error") %> prohibited this ventaunidad from being saved:</h2>

      <ul>
      <% @ventaunidad.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :mes %><br>
    <%= f.text_field :mes %>
  </div>
  <div class="field">
    <%= f.label :valor %><br>
    <%= f.number_field :valor %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ventaunidads/edit.html.erb
<h1>Editing Ventaunidad</h1>

<%= render 'form' %>

<%= link_to 'Show', @ventaunidad %> |
<%= link_to 'Back', ventaunidads_path %>

app/views/ventaunidads/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-9">
        <h2>Ventas en Unidades por Mes</h2>
        <ol class="breadcrumb">
            <li>
                <a href="<%= url_for :controller => 'dashboards', :action => 'dashboard_1' %>">Home</a>
        </li>
        <li class="active">
            Ventas en Unidades 
        </li>


        
    </ol>
</div>
        </div>
<div class="wrapper wrapper-content">
<div class="row">

<div id="archivosenlista" class="wrapper wrapper-content  animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-content">
                   
                  

                    <div class="input-group">
<%= form_tag ventaunidads_path, :method => 'get', :id => "ventaunidads_search" do %>
                        
                        <div class="col-lg-8">
                        <%= text_field_tag :search, params[:search], class: 'input form-control', :placeholder => "Buscar Mes" %>
                       </div>

                       <div class="col-lg-4">
                        <span class="input-group-btn">
                            <button type="submit" class="btn btn btn-primary" style="margin-right:15px;"> <i class="fa fa-search"></i> Buscar</button>

                            <a href="/ventaunidads" class="btn btn btn-warning"><i class="fa fa-bars" aria-hidden="true"></i>  Limpiar</a>
                       </span>

                        </div>

                        <% end %>
                    </div>
                    <div class="clients-list">


                        <div class="tab-content">
                            <div id="tab-1" class="tab-pane active">
                                <div class="full-height-scroll">
                                    <div class="table-responsive">
                                        <table class="table table-striped table-hover">
                                            <tbody>

                                    <thead>
                                      <tr>
                                       <th>Mes</th>
                                        <th>Ventas</th>
                                        
                                      
                                        <th colspan="3"></th>
                                      </tr>
                                    </thead>                                  

                                  <% @ventaunidads.each do |v| %>
                                     <tr >
                                         <td><%= v.mes %></td>
                                          <td ><%= v.valor %> </td>

                                          

                                          
                                         
                                          <td><%= link_to 'Ver', v, class: "btn btn-xs btn-outline btn-primary" %></td>
                                          <td><%= link_to 'Editar', edit_ventaunidad_path(v),  class: "btn btn-xs btn-outline btn-success" %></td>
                                          <td><%= link_to 'Eliminar', v, method: :delete, data: { confirm: 'Are you sure?' },  class: "btn btn-xs btn-outline btn-danger" %></td>

                                           
                                          

                                    </tr>


                                  <% end %>

                                            
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>

                            
                        </div>

                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
</div>
</div>

























<div class="col-lg-6" >
<%= form_tag import_ventaunidads_path, multipart: true do %>
  <%= file_field_tag :file, class: "form-control", :style => "padding-bottom:40px; margin-bottom:10px;"  %>
  <%= submit_tag "Import", class: "btn btn-primary col-lg-12", :style => "", :onclick => 'validarFile();'  %>
<% end %>

</div>


  <br><br><br><br><br><br>  <br><br>


<script>
    
    var file = document.getElementById('file');



    function validarFile(){

        if(file.value == ""){
            alert("Debe seleccionar un archivo a importar");
            
        }


    }

</script>

app/views/ventaunidads/new.html.erb
<h1>New Ventaunidad</h1>

<%= render 'form' %>

<%= link_to 'Back', ventaunidads_path %>

app/views/ventaunidads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Mes:</strong>
  <%= @ventaunidad.mes %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @ventaunidad.valor %>
</p>

<%= link_to 'Edit', edit_ventaunidad_path(@ventaunidad) %> |
<%= link_to 'Back', ventaunidads_path %>