config/routes.rb
Myapp::Application.routes.draw do


  



  resources :brandteams
  resources :accounts
  resources :permisos
  resources :operacions
  resources :seccions
  resources :rols
  resources :showrooms do
      resources :showpins
      resources :archivofolders
  end
  resources :teams
  resources :archivofolders
  resources :documentos
  resources :folders do
    resources :archivofolders
  end
  resources :payments do
    collection {post :import}
  end

  
  resources :ventaunidads do
    collection {post :import}
  end
  
  resources :channels



  resources :skugraphs do
    collection {post :import}
  end
  
  resources :velocidaddiaria
  resources :archivos do
    get 'pdf', :on => :collection
  end
  
  resources :documents
  resources :assets
    devise_for :users

 # devise_scope :user do
  #get "sign_out", to: "devise/sessions#destroy"
#end
# Session routes for Authenticatable (default)

as :user do
  get 'users/profile', :to => 'devise/registrations#edit'
end
resources :skus
  #{:controller=>"devise/sessions", :action=>"destroy"}

  get 'products/jsontodb'
  resources :users
  resources :products do
    resources :variations
    resources :skus
    collection {post :import}
  end

  # You can have the root of your site routed with "root"
  root to: 'home#index'


  # All routes
  get "dashboards/dashboard_1"
  get "dashboards/dashboard_2"
  get "dashboards/dashboard_3"
  get "dashboards/dashboard_4"
  get "dashboards/dashboard_4_1"
  get "dashboards/dashboard_5"
  get "dashboards/channels"

  get "layoutsoptions/index"
  get "layoutsoptions/off_canvas"

  get "graphs/flot"
  get "graphs/morris"
  get "graphs/rickshaw"
  get "graphs/chartjs"
  get "graphs/chartist"
  get "graphs/peity"
  get "graphs/sparkline"
  get "graphs/c3charts"

  get "mailbox/inbox"
  get "mailbox/email_view"
  get "mailbox/compose_email"
  get "mailbox/email_templates"
  get "mailbox/basic_action_email"
  get "mailbox/alert_email"
  get "mailbox/billing_email"

  get "metrics/index"

  get "widgets/index"

  get "forms/basic_forms"
  get "forms/advanced"
  get "forms/wizard"
  get "forms/file_upload"
  get "forms/text_editor"
  get "forms/markdown"

  get "appviews/contacts"
  get "appviews/profile"
  get "appviews/profile_two"
  get "appviews/contacts_two"
  get "appviews/projects"
  get "appviews/project_detail"
  get "appviews/file_menager"
  get "appviews/vote_list"
  get "appviews/calendar"
  get "appviews/faq"
  get "appviews/timeline"
  get "appviews/pin_board"
  get "appviews/teams_board"
  get "appviews/social_feed"
  get "appviews/clients"
  get "appviews/outlook_view"
  get "appviews/blog"
  get "appviews/article"
  get "appviews/issue_tracker"
  get "appviews/team"

  get "pages/search_results"
  get "pages/lockscreen"
  get "pages/invoice"
  get "pages/invoice_print"
  get "pages/login"
  get "pages/login_2"
  get "pages/forgot_password"
  get "pages/register"
  get "pages/not_found_error"
  get "pages/internal_server_error"
  get "pages/empty_page"

  get "miscellaneous/notification"
  get "miscellaneous/nestablelist"
  get "miscellaneous/timeline_second_version"
  get "miscellaneous/forum_view"
  get "miscellaneous/forum_post_view"
  get "miscellaneous/google_maps"
  get "miscellaneous/code_editor"
  get "miscellaneous/modal_window"
  get "miscellaneous/validation"
  get "miscellaneous/tree_view"
  get "miscellaneous/chat_view"
  get "miscellaneous/agile_board"
  get "miscellaneous/diff"
  get "miscellaneous/sweet_alert"
  get "miscellaneous/idle_timer"
  get "miscellaneous/spinners"
  get "miscellaneous/live_favicon"
  get "miscellaneous/masonry"
  get "miscellaneous/tour"
  get "miscellaneous/loading_buttons"
  get "miscellaneous/clipboard"
  get "miscellaneous/truncate"
  get "miscellaneous/i18support"

  get "uielements/typography"
  get "uielements/icons"
  get "uielements/draggable_panels"
  get "uielements/resizeable_panels"
  get "uielements/buttons"
  get "uielements/video"
  get "uielements/tables_panels"
  get "uielements/tabs"
  get "uielements/notifications_tooltips"
  get "uielements/badges_labels_progress"

  get "gridoptions/index"

  get "tables/static_tables"
  get "tables/data_tables"
  get "tables/foo_tables"
  get "tables/jqgrid"

  get "commerce/products_grid"
  get "commerce/products_list"
  get "commerce/product_edit"
  get "commerce/product_detail"
  get "commerce/orders"
  get "commerce/cart"
  get "commerce/payments"

  get "gallery/basic_gallery"
  get "gallery/slick_carusela"
  get "gallery/bootstrap_carusela"

  get "cssanimations/index"

  get "landing/index"

end

app/models/showroom.rb
class Showroom < ActiveRecord::Base
	dragonfly_accessor :portada
	has_many :showpins
	has_many :archivofolders
end

app/controllers/showrooms_controller.rb
class ShowroomsController < ApplicationController
  load_and_authorize_resource
  before_action :set_showroom, only: [:show, :edit, :update, :destroy]

  # GET /showrooms
  # GET /showrooms.json
  def index
    @showrooms = Showroom.all
  end

  # GET /showrooms/1
  # GET /showrooms/1.json
  def show
    @showpins = @showroom.showpins
    @archivofolders = @showroom.archivofolders
    @p = "?p=showroom&num="+params[:id]
  end

  # GET /showrooms/new
  def new
    @showroom = Showroom.new
  end

  # GET /showrooms/1/edit
  def edit
  end

  # POST /showrooms
  # POST /showrooms.json
  def create
    @showroom = Showroom.new(showroom_params)

    respond_to do |format|
      if @showroom.save
        format.html { redirect_to @showroom, notice: 'Showroom was successfully created.' }
        format.json { render action: 'show', status: :created, location: @showroom }
      else
        format.html { render action: 'new' }
        format.json { render json: @showroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /showrooms/1
  # PATCH/PUT /showrooms/1.json
  def update
    respond_to do |format|
      if @showroom.update(showroom_params)
        format.html { redirect_to @showroom, notice: 'Showroom was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @showroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /showrooms/1
  # DELETE /showrooms/1.json
  def destroy
    @showroom.destroy
    respond_to do |format|
      format.html { redirect_to showrooms_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_showroom
      @showroom = Showroom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def showroom_params
      params.require(:showroom).permit(:descripcion, :portada, :modulo, :direccion, :horario, :telefono)
    end
end

app/helpers/showrooms_helper.rb
module ShowroomsHelper
end

app/views/showrooms/_form.html.erb
<%= form_for(@showroom) do |f| %>
  <% if @showroom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@showroom.errors.count, "error") %> prohibited this showroom from being saved:</h2>

      <ul>
      <% @showroom.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :modulo %><br>
    <%= f.number_field :modulo %>
  </div>
  <div class="field">
    <%= f.label :direccion %><br>
    <%= f.text_field :direccion %>
  </div>
  <div class="field">
    <%= f.label :horario %><br>
    <%= f.text_field :horario %>
  </div>
  <div class="field">
    <%= f.label :telefono %><br>
    <%= f.text_field :telefono %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/showrooms/edit.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-9">
		<br>
        <ol class="breadcrumb">
            <li>
                <a href="/showrooms">Home</a>
        </li>
        <li>
            Showrooms
        </li>

       
    </ol>
</div>
</div>

<%= form_for(@showroom) do |f| %>
  <% if @showroom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@showroom.errors.count, "error") %> prohibited this showroom from being saved:</h2>

      <ul>
      <% @showroom.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
 <% end %>

<div class="wrapper wrapper-content animated fadeInRight ecommerce">
	<div class="row">
    	<div class="col-lg-12">
       		 
           
  					<div class="field">
    					<%= f.label :descripcion %><br>
    					<%= f.text_field :descripcion, class: "form-control", placeholder: "Descripcion", :required => true %>
  					</div>
  					<br>

  					<div class="field">
    					<%= f.label :modulo %><br>
    					<%= f.number_field :modulo, class: "form-control", placeholder: "Modulo(s)", :required => true %>
  					</div>
  					<br>
  					<div class="field">
    					<%= f.label :telefono %><br>
    					<%= f.text_field :telefono, class: "form-control", placeholder: "Teléfono", :required => true %>
  					</div>
  					<br>
  					<div class="field">
    					<%= f.label :direccion %><br>
    					<%= f.text_field :direccion , class: "form-control", placeholder: "Direccion", :required => true %>
  					</div>
            <br>

            <div class="field">
              <%= f.label :Portada %><br>
              <%= f.file_field :portada , class: "form-control", style:  "padding-bottom:40px; margin-bottom:10px;" %>
            </div>

  					<div class="field">
    					<%= f.label :horario %><br>
    					<%= f.text_field :horario , class: "form-control", placeholder: "Horario", :required => true %>
  					</div>
            <br>
			







  					<div class="actions">
    					<input type="submit" value="Actualizar" class="btn btn-primary col-lg-3">
  					</div>




					<% end %>
			
		</div>
	</div>
</div>

<script>
  
  var colorPicker = document.querySelector('.js-color-picker'),
    colorText = document.querySelector('.js-color-text');

function formatHexcode() {
    var color = colorPicker.value;

    if (color[1] === color[2] &&
        color[3] === color[4] &&
        color[5] === color[6]) {
        color = '#' + color[1] + color[3] + color[5];
    }

    return color;
}

function displayHexcode() {
    colorText.innerHTML = formatHexcode();
}

colorPicker.addEventListener('change', displayHexcode);
displayHexcode();

</script>

<script>
	$(".date-picker").datepicker();

	$( "#date-picker-3" ).change(function() {
  		$( "#fecha" ).val($( "#date-picker-3" ).val());
});

  $( ".js-color-picker" ).change(function() {
      $( "#colorrails" ).val($( ".js-color-picker" ).val());
});

 $( "#colorrails" ).val($( ".js-color-picker" ).val());
  

$(".date-picker").on("change", function () {
    var id = $(this).attr("id");
    var val = $("label[for='" + id + "']").text();
    $("#msg").text(val + " changed");
});
</script>

<style>
#colorrails{

display:none;
}

#fecha{
	display: none;
}

.ui-datepicker {
	background-color: #fff;
	border: 1px solid #66AFE9;
	border-radius: 4px;
	box-shadow: 0 0 8px rgba(102,175,233,.6);
	
}
.ui-datepicker a,
.ui-datepicker a:hover {
	text-decoration: none;
}
.ui-datepicker a:hover,
.ui-datepicker td:hover a {
	color: #2A6496;
	-webkit-transition: color 0.1s ease-in-out;
	   -moz-transition: color 0.1s ease-in-out;
	     -o-transition: color 0.1s ease-in-out;
	        transition: color 0.1s ease-in-out;
}
.ui-datepicker .ui-datepicker-header {
	margin-bottom: 4px;
	text-align: center;
}
.ui-datepicker .ui-datepicker-title {
	font-weight: 700;
}
.ui-datepicker .ui-datepicker-prev,
.ui-datepicker .ui-datepicker-next {
	cursor: default;
	font-family: 'Glyphicons Halflings';
	-webkit-font-smoothing: antialiased;
	font-style: normal;
	font-weight: normal;
	height: 20px;
	line-height: 1;
	margin-top: 2px;
	width: 30px;
}
.ui-datepicker .ui-datepicker-prev {
	float: left;
	text-align: left;
}
.ui-datepicker .ui-datepicker-next {
	float: right;
	text-align: right;
}
.ui-datepicker .ui-datepicker-prev:before {
	content: "\e079";
}
.ui-datepicker .ui-datepicker-next:before {
	content: "\e080";
}
.ui-datepicker .ui-icon {
	display: none;
}
.ui-datepicker .ui-datepicker-calendar {
  table-layout: fixed;
	width: 100%;
}
.ui-datepicker .ui-datepicker-calendar th,
.ui-datepicker .ui-datepicker-calendar td {
	text-align: center;
	padding: 4px 0;
}
.ui-datepicker .ui-datepicker-calendar td {
	border-radius: 4px;
	-webkit-transition: background-color 0.1s ease-in-out, color 0.1s ease-in-out;
	   -moz-transition: background-color 0.1s ease-in-out, color 0.1s ease-in-out;
	     -o-transition: background-color 0.1s ease-in-out, color 0.1s ease-in-out;
	        transition: background-color 0.1s ease-in-out, color 0.1s ease-in-out;
}
.ui-datepicker .ui-datepicker-calendar td:hover {
	background-color: #eee;
	cursor: pointer;
}
.ui-datepicker .ui-datepicker-calendar td a {
	text-decoration: none;
}
.ui-datepicker .ui-datepicker-current-day {
	background-color: #4289cc;
}
.ui-datepicker .ui-datepicker-current-day a {
	color: #fff
}
.ui-datepicker .ui-datepicker-calendar .ui-datepicker-unselectable:hover {
	background-color: #fff;
	cursor: default;
}

</style>

app/views/showrooms/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-9">
        <br>
        <ol class="breadcrumb">
        <li>
                <a href="/showrooms">Home</a>
        </li>

        <li >
            Showrooms
        </li>

         <% if can? :create, Showroom %>
        <li>
            <strong><%= link_to 'Add New Showroom', new_showroom_path %></strong>

        </li>
        <%end%>
       
    </ol>
</div>
</div>

<br>
<div class="row">

<% @showrooms.each do |show| %>

    <div class="col-lg-4">
        <div class="widget-head-color-box p-lg text-center" style=" background-color:#436871; color:white;">




        



            <div class="m-b-md">
                <h2 class="font-bold no-margins">
                   <%= show.descripcion %>
                </h2>
               

                
               
            </div>
            <img src="<%= show.portada.url %>" class="img-circle circle-border m-b-md" alt="profile" style="width:150px; height:150px;">
            <div>
                
                <span><strong>Modulo(s):</strong> <%= show.modulo %></span> 
                
            </div>
        </div>
        <div class="widget-text-box">
            <h4 class="media-heading"><i class="fa fa-map-marker" aria-hidden="true"></i>  Direccion: </h4>
            <p><%= show.direccion %></p>

            <h4 class="media-heading"><i class="fa fa-clock-o" aria-hidden="true"></i>
            Horario: </h4>
            <p><%= show.horario %></p>

            <h4 class="media-heading"><i class="fa fa-phone" aria-hidden="true"></i>

            Teléfono: </h4>
            <p><%= show.telefono %></p>
            
            <div class="text-right">
               


                <%= link_to "Show", show, class: "btn btn-xs btn-primary" %>
                
                <% if can? :delete, Showroom %>
                <%= link_to 'Delete', show, method: :delete, data: { confirm: 'Are you sure in delete this showroom' }, class: "btn btn-xs btn-danger" %>
                <%end%>

                
            </div>
        </div>
    </div>

    <% end %>


</div>


 





<br><br><br><br>
    

app/views/showrooms/show.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-9">
		<br>
        <ol class="breadcrumb">
            <li>
                <a href="/showrooms">Home</a>
        </li>
        <li>
            Showrooms
        </li>
        <% if can? :create, Showroom %>
        <li>
            <a href="/archivofolders/new/<%= @p %>">Add new file</a>
        </li>
        <%end%>

       
    </ol>
</div>
</div>

<%= form_for(@showroom) do |f| %>
  <% if @showroom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@showroom.errors.count, "error") %> prohibited this showroom from being saved:</h2>

      <ul>
      <% @showroom.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
 <% end %>

<div class="wrapper wrapper-content animated fadeInRight ecommerce">
	<div class="row">
    	<div class="col-lg-12">
       		 
           
    <div class="col-lg-9">
        <div class="widget-head-color-box p-lg text-center" style=" background-color:#436871; color:white;">




        



            <div class="m-b-md">
                <h2 class="font-bold no-margins">
                   <%= @showroom.descripcion %>
                </h2>
               

                
               
            </div>
            <img src="<%= @showroom.portada.url %>" class="img-circle circle-border m-b-md" alt="profile" style="width:150px; height:150px;">
            <div>
                
                <span><strong>Modulo(s):</strong> <%= @showroom.modulo %></span> 
                
            </div>
        </div>
        <div class="widget-text-box" style="height:400px;">
          
          <div class="col-lg-6">
            <h4 class="media-heading"><i class="fa fa-map-marker" aria-hidden="true"></i>  Direccion: </h4>
            <p><%= @showroom.direccion %></p>

            <h4 class="media-heading"><i class="fa fa-clock-o" aria-hidden="true"></i>
            Horario: </h4>
            <p><%= @showroom.horario %></p>

            <h4 class="media-heading"><i class="fa fa-phone" aria-hidden="true"></i>

            Teléfono: </h4>
            <p><%= @showroom.telefono %></p>
            
           
               
        <% if can? :update, Showpin %>
        <%= link_to 'Edit', edit_showroom_path(@showroom), class: "btn btn-xs btn-warning" %>
        <%end%>      

                
           
          </div>

          <div class="col-lg-6">
    <h4 class="media-heading"><i class="fa fa-check" aria-hidden="true"></i>
  Archivos: </h4>
    <br>
    <!-- archivos -->
    <div id="listaarchivos">  

    <%= form_for (@showroom) do |f| %>
        <% @showroom.archivofolders.each do |af| %>

          


    <div class="carpeta col-lg-4" style="text-align:center;">

      <a title="Abrir Archivo" class="linkiconarchivo" href="<%= af.filefolder.url %>">

     <% if af.filefolder.ext == 'png' or af.filefolder.ext == 'jpg' or af.filefolder.ext == 'jpeg' %>
      
      <i style="font-size:40px; left:50%;" class="fa fa-file-image-o" aria-hidden="true"></i>

     <%elsif af.filefolder.ext == 'xls' or af.filefolder.ext == 'csv' or af.filefolder.ext == 'xlsx'%>
      <i  style="font-size:40px; left:50%;" class="fa fa-file-excel-o" aria-hidden="true"></i>
      <%elsif af.filefolder.ext == 'doc' %>
      <i style="font-size:40px; left:50%;" class="fa fa-file-word-o" aria-hidden="true"></i>
       <%elsif af.filefolder.ext == 'txt' %>
      <i style="font-size:40px; left:50%;" class="fa fa-file-text-o" aria-hidden="true"></i>
      <%elsif af.filefolder.ext == 'zip' or af.filefolder.ext == 'tar' or af.filefolder.ext == 'rar' or af.filefolder.ext == 'tgz' %>
      <i style="font-size:40px; left:50%;" class="fa fa-file-archive-o" aria-hidden="true"></i>
      <%elsif af.filefolder.ext == 'pdf' %>
      <i style="font-size:40px; left:50%;" class="fa fa-file-pdf-o" aria-hidden="true"></i>
      <%elsif af.filefolder.ext == 'html' %>
      <i style="font-size:40px; left:50%;" class="fa fa-file-code-o" aria-hidden="true"></i>
      <%else %>
      <i style="font-size:40px; left:50%;"  class="fa fa-file-o" aria-hidden="true"></i>

      <%end%>

      </a>

     <a title="Editar Archivo" class="linkarchivo" href="/archivofolders/<%=af.id%>/edit"><%= af.nombre %></a>


     

    </div>
    


    
        <%end%>
    <%end%>
</div>
    <!-- archivos -->
  
          </div>
          
        </div>

    <br><br>


    </div>

	<!-- pines -->	

 	<div class="col-lg-3" >
<ul class="notes" style="margin-left:-30px;">
      <%= form_for (@showroom) do |f| %>
        <% @showroom.showpins.each do |sp| %>

    <li>
        <div>
            <small><%= sp.created_at %></small>
            <h4><%= sp.titulo %></h4>
            <p><%= sp.nota %></p>
 <% if can? :delete, Showpin %>
<%= link_to 'Delete', showroom_showpin_path(@showroom, sp), :confirm => 'Are you sure?', :method => :delete, class: "btn btn-xs btn-outline btn-danger" %>
<%end%>
        </div>
    </li>

        <% end %>
        <%end%>
   
</ul>

<br>

<% if can? :create, Showpin %>
<%= form_for [@showroom, Showpin.new] do |f| %>

<div class="col-lg-12 ">
    
                    <div class="field">
                        <%= f.label :titulo %><br>
                        <%= f.text_field :titulo, class: "form-control", placeholder: "Titulo", :required => true %>
                    </div>
                    <br>
    
                    <div class="field">
                        <%= f.label :nota %><br>
                        <%= f.text_area :nota, class: "form-control", placeholder: "Nota", :required => true %>
                    </div>
                    <br>
                    <div class="actions">
                        <input type="submit" value="Guardar" class="btn btn-primary col-lg-12">
                    </div>
                    <br><br>

</div>


<% end %>
<%end%>
	</div>
	<!-- pines -->



					<% end %>
			
		</div>
	</div>
</div>

<script>
  
  var colorPicker = document.querySelector('.js-color-picker'),
    colorText = document.querySelector('.js-color-text');

function formatHexcode() {
    var color = colorPicker.value;

    if (color[1] === color[2] &&
        color[3] === color[4] &&
        color[5] === color[6]) {
        color = '#' + color[1] + color[3] + color[5];
    }

    return color;
}

function displayHexcode() {
    colorText.innerHTML = formatHexcode();
}

colorPicker.addEventListener('change', displayHexcode);
displayHexcode();

</script>

<script>
	$(".date-picker").datepicker();

	$( "#date-picker-3" ).change(function() {
  		$( "#fecha" ).val($( "#date-picker-3" ).val());
});

  $( ".js-color-picker" ).change(function() {
      $( "#colorrails" ).val($( ".js-color-picker" ).val());
});

 $( "#colorrails" ).val($( ".js-color-picker" ).val());
  

$(".date-picker").on("change", function () {
    var id = $(this).attr("id");
    var val = $("label[for='" + id + "']").text();
    $("#msg").text(val + " changed");
});
</script>

<style>
#colorrails{

display:none;
}

#fecha{
	display: none;
}

.ui-datepicker {
	background-color: #fff;
	border: 1px solid #66AFE9;
	border-radius: 4px;
	box-shadow: 0 0 8px rgba(102,175,233,.6);
	
}
.ui-datepicker a,
.ui-datepicker a:hover {
	text-decoration: none;
}
.ui-datepicker a:hover,
.ui-datepicker td:hover a {
	color: #2A6496;
	-webkit-transition: color 0.1s ease-in-out;
	   -moz-transition: color 0.1s ease-in-out;
	     -o-transition: color 0.1s ease-in-out;
	        transition: color 0.1s ease-in-out;
}
.ui-datepicker .ui-datepicker-header {
	margin-bottom: 4px;
	text-align: center;
}
.ui-datepicker .ui-datepicker-title {
	font-weight: 700;
}
.ui-datepicker .ui-datepicker-prev,
.ui-datepicker .ui-datepicker-next {
	cursor: default;
	font-family: 'Glyphicons Halflings';
	-webkit-font-smoothing: antialiased;
	font-style: normal;
	font-weight: normal;
	height: 20px;
	line-height: 1;
	margin-top: 2px;
	width: 30px;
}
.ui-datepicker .ui-datepicker-prev {
	float: left;
	text-align: left;
}
.ui-datepicker .ui-datepicker-next {
	float: right;
	text-align: right;
}
.ui-datepicker .ui-datepicker-prev:before {
	content: "\e079";
}
.ui-datepicker .ui-datepicker-next:before {
	content: "\e080";
}
.ui-datepicker .ui-icon {
	display: none;
}
.ui-datepicker .ui-datepicker-calendar {
  table-layout: fixed;
	width: 100%;
}
.ui-datepicker .ui-datepicker-calendar th,
.ui-datepicker .ui-datepicker-calendar td {
	text-align: center;
	padding: 4px 0;
}
.ui-datepicker .ui-datepicker-calendar td {
	border-radius: 4px;
	-webkit-transition: background-color 0.1s ease-in-out, color 0.1s ease-in-out;
	   -moz-transition: background-color 0.1s ease-in-out, color 0.1s ease-in-out;
	     -o-transition: background-color 0.1s ease-in-out, color 0.1s ease-in-out;
	        transition: background-color 0.1s ease-in-out, color 0.1s ease-in-out;
}
.ui-datepicker .ui-datepicker-calendar td:hover {
	background-color: #eee;
	cursor: pointer;
}
.ui-datepicker .ui-datepicker-calendar td a {
	text-decoration: none;
}
.ui-datepicker .ui-datepicker-current-day {
	background-color: #4289cc;
}
.ui-datepicker .ui-datepicker-current-day a {
	color: #fff
}
.ui-datepicker .ui-datepicker-calendar .ui-datepicker-unselectable:hover {
	background-color: #fff;
	cursor: default;
}

</style>